# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!
target 'NewDawn' do
  # Pods for NewDawn
  pod 'SwiftKeychainWrapper', '~> 3.0'
  pod 'MessageKit', '~> 3.0.0'
  pod 'MessageInputBar'
  pod 'PusherSwift'
  pod 'Alamofire', '~> 4.0'
  pod 'PushNotifications', '~> 1.2.0'
  pod 'Kingfisher', '~> 5.0'
  target 'NewDawnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewDawnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end