# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target 'NewDawn' do
  # Pods for NewDawn
  pod 'SwiftKeychainWrapper', '~> 3.0'
  pod 'MessageKit'
  pod 'PusherSwift'
  pod 'Alamofire', '~> 4.0'
  pod 'PushNotifications', '~> 1.2.0'
  target 'NewDawnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewDawnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
