# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'NewDawn' do
  # Pods for NewDawn
  pod 'SwiftKeychainWrapper', '~> 3.0'
  pod 'MessageKit'
  pod 'PusherSwift'
  pod 'Alamofire', '~> 4.0'
  target 'NewDawnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewDawnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
